// LOAD FILMS
const LOAD_FILMS = 'film/LOAD_FILMS';
const LOAD_FILMS_SUCCESS = 'film/LOAD_FILMS_SUCCESS';
const LOAD_FILMS_FAIL = 'film/LOAD_FILMS_FAIL';

// ADD FILM
const ADD_FILM = 'film/ADD_FILM';
const ADD_FILM_SUCCESS = 'film/ADD_FILM_SUCCESS';
const ADD_FILM_FAIL = 'film/ADD_FILM_FAIL';

// UPDATE_FILM
const UPDATE_FILM = 'film/UPDATE_FILM';
const UPDATE_FILM_SUCCESS = 'film/UPDATE_FILM_SUCCESS';
const UPDATE_FILM_FAIL = 'film/UPDATE_FILM_FAIL';

// DELETE_FILM
const DELETE_FILM = 'film/DELETE_FILM';
const DELETE_FILM_SUCCESS = 'film/DELETE_FILM_SUCCESS';
const DELETE_FILM_FAIL = 'film/DELETE_FILM_FAIL';

const types = {
  LOAD_FILMS,
  LOAD_FILMS_SUCCESS,
  LOAD_FILMS_FAIL,
  STORE_FILMS,
  ADD_FILM,
  ADD_FILM_SUCCESS,
  ADD_FILM_FAIL,
  UPDATE_FILM,
  UPDATE_FILM_SUCCESS,
  UPDATE_FILM_FAIL,
  DELETE_FILM,
  DELETE_FILM_SUCCESS,
  DELETE_FILM_FAIL,
};

export default types;
